---
title: "Projekt"
output: html_notebook
author:
    - Anisa Kapri
    - Andri Reveli
    - Dionis Hysko
date: 2021-06-01
---


## Hyrje

Librarite dhe paketat qe do te perdoren ne kete projekt:

```{r}
library(esquisse)
library(ggplot2)
library(reshape)
library(Rcmdr)
library(readxl)

source("scripts/clean.R")
source("scripts/utils.R")
```


```{r}
# Global constants
months = c("Janar", "Shkurt", "Mars", "Prill", "Maj", "Qershor", "Korrik", "Gusht", "Shtator", "Tetor", "Nentor", "Dhjetor")

years2016_2021 = c(2016, 2017, 2018, 2019, 2020, 2021)
```


```{r}
# test hi katror per pavaresine e hyrje daljeve nga viti

# read the data
hyrje_dalje_vjetore = read_excel(
    path = "datasets/hyrje-dalje-vjetore.xlsx", 
    col_types = c("numeric", "numeric", "numeric", "text")
)

## convert to contigency table
#y = as.matrix(data.frame(x$Albania.citizens, x$Foreign.citizens))
#row.names(y) = x$Year
#colnames(y) = c("Shqiptare", "Te huaj")
#y = as.table(y)
print(hyrje_dalje_vjetore)

## chi square test
#chisq.test(y)
```


diagrami

```{r}
ggplot(
    hyrje_dalje_vjetore, 
    aes(x = Viti, y = `Hyrje (total)`, fill = Shtetas)
) + 
    geom_bar(stat="identity",position = "dodge", alpha = 0.5) + 
    labs(y = "Hyrje", title = "Tabela e hyrjeve") + 
    coord_cartesian(ylim = c(0, 6500000))

ggplot(
    hyrje_dalje_vjetore, 
    aes(x = Viti, y = `Dalje (total)`, fill = Shtetas)
) + 
    geom_bar(stat="identity",position = "dodge", alpha = 0.5) + 
    labs(y = "Dalje", title = "Tabela e daljeve") + 
    coord_cartesian(ylim = c(0, 6500000))
```

INTERPRETIM



Te dhenat vjetore

```{r}
# read data
hyrje = readXL(
    "datasets/tab-4.xlsx", 
    rownames = FALSE, 
    header = TRUE, 
    na = "", 
    sheet = "Sheet 1", 
    stringsAsFactors = TRUE
)

print(hyrje)


# build data frame for each year
hyrje2016 = build_vector(hyrje, 1, seq(2, 3))
hyrje2017 = build_vector(hyrje, 1, seq(4, 15))
hyrje2018 = build_vector(hyrje, 1, seq(16, 27))
hyrje2019 = build_vector(hyrje, 1, seq(28, 39))
hyrje2020 = build_vector(hyrje, 1, seq(40, 51))
hyrje2021 = build_vector(hyrje, 1, seq(52, 53))

year_based = list(hyrje2016, hyrje2017, hyrje2018, hyrje2019, hyrje2020, hyrje2021)
attributes(year_based) = list(
    names = years2016_2021,
    row.names = 1:length(x), 
    class = 'data.frame'
)


# plot
to_plot = data.frame(
    vitet2016_2021 = years2016_2021,
    viti_2016 = year_based$`2016`,
    viti_2017 = year_based$`2017`,
    viti_2018 = year_based$`2018`,
    viti_2019 = year_based$`2019`,
    viti_2020 = year_based$`2020`,
    viti_2021 = year_based$`2021`
)
melted = melt(to_plot, id="vitet2016_2021")

ggplot(melted, aes(x = vitet2016_2021, y = value, fill = variable)) + 
    geom_boxplot(outlier.colour = "red", outlier.shape = 1) + 
    labs(
        title = "Hyrje te shtetasve te huaj per qellime pushimi, vizita etj",
        x = "Viti",
        y = "Hyrje" 
    ) + 
    guides(fill = FALSE)
```


Te dhenat mujore

```{r}
# build data frame for each month

hyrje_jan = build_vector(hyrje, 1, seq(4, 53, 12))
hyrje_feb = build_vector(hyrje, 1, seq(5, 53, 12))
hyrje_mar = build_vector(hyrje, 1, seq(6, 53, 12))
hyrje_apr = build_vector(hyrje, 1, seq(7, 53, 12))
hyrje_may = build_vector(hyrje, 1, seq(8, 53, 12))
hyrje_jun = build_vector(hyrje, 1, seq(9, 53, 12))
hyrje_jul = build_vector(hyrje, 1, seq(10, 53, 12))
hyrje_aug = build_vector(hyrje, 1, seq(11, 53, 12))
hyrje_sep = build_vector(hyrje, 1, seq(12, 53, 12))
hyrje_oct = build_vector(hyrje, 1, seq(13, 53, 12))
hyrje_nov = build_vector(hyrje, 1, seq(2, 53, 12))
hyrje_dec = build_vector(hyrje, 1, seq(3, 53, 12))

month_based = list(
    hyrje_jan,
    hyrje_feb,
    hyrje_mar,
    hyrje_apr,
    hyrje_may,
    hyrje_jun,
    hyrje_jul,
    hyrje_aug,
    hyrje_sep,
    hyrje_oct,
    hyrje_nov,
    hyrje_dec
)
attributes(month_based) = list(
    names = months,
    row.names = 1:max(length(x), 12), 
    class = 'data.frame'
)

# plot
boxplot(month_based, xlab = "Muaji", ylab = "Hyrje te shtetasve te huaj per qellime pushimi")
```


INTERPRETIM

Shenim: Injoro 2016 dhe 2021 sepse ka shume pak te dhena
